### PR TITLE
Fix all lineage-15.1 build error

### PR DESCRIPTION
**Pull request by micky387**
no more stuff inside

We need to repopick some no merged files too
# selinux (in waiting final work)
repopick 203500 203501
# Camera Hal V1
repopick 198106 198107 198113 201336

### CODE REVIEW

**Comment by github-cygwin** [comment]
Are these patches supposed to be in cm-14.1 or rather in a (yet to be created) lineage-15.1 branch?

**Comment by micky387** [comment]
you need to creat a lineage-15.1 branch. it's only for this branch

**Comment by micky387** [comment]
i need to edit comment in OP because first repopick are wrong. staging branch are deprecated now.

**Comment by github-cygwin** [comment]
I created a lineage-15.1 branch so you can rebase the patches to that branch and fix the comments.

**Pull request closed without merging**
